version: '3.8'

services:
  pvt:
    container_name: pvt
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8001:8001"
    networks:
      gpncr-bridge:
        aliases:
          - pvt


networks:
  gpncr-bridge:
    external:
      name: gpncr-network